name: emoji

# Cell state
phenotype_size: 3  # RGB
hidden_size: 12  # In ``Growing Neural Cellular Automata`` paper, the total cell state size is 16 = 3 + 1 + 12.
fire_rate: 0.5

# Emoji
emojis: "ğŸ¦ğŸ˜€ğŸ’¥ğŸ‘ğŸ ğŸ¦‹ğŸğŸ•¸ğŸ¥¨ğŸ„"
n_emojis: 2
emoji_size: 40
emoji_padding: 16

# Train
n_iterations: 10_000
log_period: 100
batch_size: 8
pool_size: 1024
learning_rate: 2e-3
n_damages: 3
