name: emoji

# Cell state
phenotype_size: 3  # RGB
hidden_size: 12  # In ``Growing Neural Cellular Automata`` paper, the total cell state size is 16 = 3 + 1 + 0 + 12.
genotype_size: 0  # In ``Growing Neural Cellular Automata`` paper, there is no genotype.
fire_rate: 0.5

# Emoji
emojis: "ğŸ¦ğŸ˜€ğŸ’¥ğŸ‘ğŸ ğŸ¦‹ğŸğŸ•¸ğŸ¥¨ğŸ„"
emoji_size: 40
emoji_padding: 16

# Train
batch_size: 8
pool_size: 1024
learning_rate: 2e-3

# Experiment
experiment_type: "Regenerating"  # ["Growing", "Persistent", "Regenerating"]
